name: E2E-TEST for AutoMQ S3Stream
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 's3stream/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: "maven"
      - name: Build s3stream
        working-directory: ./s3stream
        run: mvn clean install -U -DskipTests
      - uses: actions/checkout@v3
        with:
          repository: AutoMQ/s3stream-e2e
          ref: main
          path: s3stream-e2e
          token: ${{ secrets.PAT_E2E }}
      - name: Change s3stream version
        run: |
          export S3STREAM_VERSION=$(cat s3stream/target/maven-archiver/pom.properties | grep version | awk -F '=' '{print $2}')
          echo "change s3stream version of e2e test to $S3STREAM_VERSION"
          sed -i "s/<s3stream.version>.*<\/s3stream.version>/<s3stream.version>$S3STREAM_VERSION<\/s3stream.version>/g" s3stream-e2e/pom.xml
          export LINE_START=$(awk '/<repositories>/{print NR}' s3stream-e2e/pom.xml)
          export LINE_END=$(awk '/<\/repositories>/{print NR}' s3stream-e2e/pom.xml)
          sed -i "${LINE_START},${LINE_END}d" s3stream-e2e/pom.xml
          cat s3stream-e2e/pom.xml
      - name: Run tests
        working-directory: ./s3stream-e2e
        run: mvn test -pl integration
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/surefire-reports/TEST-*.xml'
          annotate_only: true
          include_passed: true
          detailed_summary: true